# Student: Joe Castrejon
# Description: A simple makefile for assignment 2 in the course ECEN 5713 Advanced Embedded Software development
# Date: 

CC=$(CROSS_COMPILE)gcc
OUTPUT=writer

default: all

default:
	$(CC) writer.c -o $(OUTPUT)			

clean:
	rm writer

